-- Real countries (195)
INSERT INTO countries (code, name, is_fictional) VALUES
('AFG', 'Afghanistan', false),
('ALB', 'Albania', false),
('DZA', 'Algeria', false),
('AND', 'Andorra', false),
('AGO', 'Angola', false),
('ATG', 'Antigua and Barbuda', false),
('ARG', 'Argentina', false),
('ARM', 'Armenia', false),
('AUS', 'Australia', false),
('AUT', 'Austria', false),
('AZE', 'Azerbaijan', false),
('BHS', 'Bahamas', false),
('BHR', 'Bahrain', false),
('BGD', 'Bangladesh', false),
('BRB', 'Barbados', false),
('BLR', 'Belarus', false),
('BEL', 'Belgium', false),
('BLZ', 'Belize', false),
('BEN', 'Benin', false),
('BTN', 'Bhutan', false),
('BOL', 'Bolivia', false),
('BIH', 'Bosnia and Herzegovina', false),
('BWA', 'Botswana', false),
('BRA', 'Brazil', false),
('BRN', 'Brunei', false),
('BGR', 'Bulgaria', false),
('BFA', 'Burkina Faso', false),
('BDI', 'Burundi', false),
('KHM', 'Cambodia', false),
('CMR', 'Cameroon', false),
('CAN', 'Canada', false),
('CPV', 'Cape Verde', false),
('CAF', 'Central African Republic', false),
('TCD', 'Chad', false),
('CHL', 'Chile', false),
('CHN', 'China', false),
('COL', 'Colombia', false),
('COM', 'Comoros', false),
('COG', 'Congo', false),
('CRI', 'Costa Rica', false),
('HRV', 'Croatia', false),
('CUB', 'Cuba', false),
('CYP', 'Cyprus', false),
('CZE', 'Czech Republic', false),
('COD', 'Democratic Republic of the Congo', false),
('DNK', 'Denmark', false),
('DJI', 'Djibouti', false),
('DMA', 'Dominica', false),
('DOM', 'Dominican Republic', false),
('ECU', 'Ecuador', false),
('EGY', 'Egypt', false),
('SLV', 'El Salvador', false),
('GNQ', 'Equatorial Guinea', false),
('ERI', 'Eritrea', false),
('EST', 'Estonia', false),
('ETH', 'Ethiopia', false),
('FJI', 'Fiji', false),
('FIN', 'Finland', false),
('FRA', 'France', false),
('GAB', 'Gabon', false),
('GMB', 'Gambia', false),
('GEO', 'Georgia', false),
('DEU', 'Germany', false),
('GHA', 'Ghana', false),
('GRC', 'Greece', false),
('GRD', 'Grenada', false),
('GTM', 'Guatemala', false),
('GIN', 'Guinea', false),
('GNB', 'Guinea-Bissau', false),
('GUY', 'Guyana', false),
('HTI', 'Haiti', false),
('HND', 'Honduras', false),
('HUN', 'Hungary', false),
('ISL', 'Iceland', false),
('IND', 'India', false),
('IDN', 'Indonesia', false),
('IRN', 'Iran', false),
('IRQ', 'Iraq', false),
('IRL', 'Ireland', false),
('ISR', 'Israel', false),
('ITA', 'Italy', false),
('CIV', 'Ivory Coast', false),
('JAM', 'Jamaica', false),
('JPN', 'Japan', false),
('JOR', 'Jordan', false),
('KAZ', 'Kazakhstan', false),
('KEN', 'Kenya', false),
('KIR', 'Kiribati', false),
('KWT', 'Kuwait', false),
('KGZ', 'Kyrgyzstan', false),
('LAO', 'Laos', false),
('LVA', 'Latvia', false),
('LBN', 'Lebanon', false),
('LSO', 'Lesotho', false),
('LBR', 'Liberia', false),
('LBY', 'Libya', false),
('LIE', 'Liechtenstein', false),
('LTU', 'Lithuania', false),
('LUX', 'Luxembourg', false),
('MDG', 'Madagascar', false),
('MWI', 'Malawi', false),
('MYS', 'Malaysia', false),
('MDV', 'Maldives', false),
('MLI', 'Mali', false),
('MLT', 'Malta', false),
('MHL', 'Marshall Islands', false),
('MRT', 'Mauritania', false),
('MUS', 'Mauritius', false),
('MEX', 'Mexico', false),
('FSM', 'Micronesia', false),
('MDA', 'Moldova', false),
('MCO', 'Monaco', false),
('MNG', 'Mongolia', false),
('MNE', 'Montenegro', false),
('MAR', 'Morocco', false),
('MOZ', 'Mozambique', false),
('MMR', 'Myanmar', false),
('NAM', 'Namibia', false),
('NRU', 'Nauru', false),
('NPL', 'Nepal', false),
('NLD', 'Netherlands', false),
('NZL', 'New Zealand', false),
('NIC', 'Nicaragua', false),
('NER', 'Niger', false),
('NGA', 'Nigeria', false),
('PRK', 'North Korea', false),
('MKD', 'North Macedonia', false),
('NOR', 'Norway', false),
('OMN', 'Oman', false),
('PAK', 'Pakistan', false),
('PLW', 'Palau', false),
('PSE', 'Palestine', false),
('PAN', 'Panama', false),
('PNG', 'Papua New Guinea', false),
('PRY', 'Paraguay', false),
('PER', 'Peru', false),
('PHL', 'Philippines', false),
('POL', 'Poland', false),
('PRT', 'Portugal', false),
('QAT', 'Qatar', false),
('ROU', 'Romania', false),
('RUS', 'Russia', false),
('RWA', 'Rwanda', false),
('KNA', 'Saint Kitts and Nevis', false),
('LCA', 'Saint Lucia', false),
('VCT', 'Saint Vincent and the Grenadines', false),
('WSM', 'Samoa', false),
('SMR', 'San Marino', false),
('STP', 'Sao Tome and Principe', false),
('SAU', 'Saudi Arabia', false),
('SEN', 'Senegal', false),
('SRB', 'Serbia', false),
('SYC', 'Seychelles', false),
('SLE', 'Sierra Leone', false),
('SGP', 'Singapore', false),
('SVK', 'Slovakia', false),
('SVN', 'Slovenia', false),
('SLB', 'Solomon Islands', false),
('SOM', 'Somalia', false),
('ZAF', 'South Africa', false),
('KOR', 'South Korea', false),
('SSD', 'South Sudan', false),
('ESP', 'Spain', false),
('LKA', 'Sri Lanka', false),
('SDN', 'Sudan', false),
('SUR', 'Suriname', false),
('SWZ', 'Eswatini', false),
('SWE', 'Sweden', false),
('CHE', 'Switzerland', false),
('SYR', 'Syria', false),
('TWN', 'Taiwan', false),
('TJK', 'Tajikistan', false),
('TZA', 'Tanzania', false),
('THA', 'Thailand', false),
('TLS', 'Timor-Leste', false),
('TGO', 'Togo', false),
('TON', 'Tonga', false),
('TTO', 'Trinidad and Tobago', false),
('TUN', 'Tunisia', false),
('TUR', 'Turkey', false),
('TKM', 'Turkmenistan', false),
('TUV', 'Tuvalu', false),
('UGA', 'Uganda', false),
('UKR', 'Ukraine', false),
('ARE', 'United Arab Emirates', false),
('GBR', 'United Kingdom', false),
('USA', 'United States', false),
('URY', 'Uruguay', false),
('UZB', 'Uzbekistan', false),
('VUT', 'Vanuatu', false),
('VAT', 'Vatican City', false),
('VEN', 'Venezuela', false),
('VNM', 'Vietnam', false),
('YEM', 'Yemen', false),
('ZMB', 'Zambia', false),
('ZWE', 'Zimbabwe', false);

-- Fictional countries
INSERT INTO countries (code, name, is_fictional) VALUES
('ANT', 'Antkowian Empire', true),
('RMW', 'Republic of Marcinów-Wojtkowski', true),
('JAK', 'Jakubowo', true),
('ALA', 'Alanowo', true),
('STA', 'Staśowianie', true),
('JAD', 'Jadziowo', true),
('AFR', 'Afryka', true),
('KOL', 'Kołołoszewowo', true),
('ROM', 'Romanie', true),
('GRZ', 'Grześiowo', true),
('PAC', 'Pacusiowo', true),
('PIN', 'Pinkowiczowo', true);
